kingfisherio/Fishsims

Networking
Redux
client/socket.js
server/socket/index.js

initial sockets

---

client/components/Game.js
client/script/circles.js
client/store/circles.js
client/store/index.js
server/socket/index.js

Successfully tested some basic functionality where:
- player can add a circle locally & emit this to the server
- server adds the circle to an array of all player's circles and io.emits this to all players
- each player draws all circles received from server

testing drawing with multiple client sockets

---

Redux
server/socket/index.js

Charlie found a fix to gamestate data not being initially sent to clients upon socket connect.

fixed issue with gamestate not rendering on initial arrival at page

---

client/components/Game.js
client/script/circles.js
client/store/index.js
client/store/map.js
client/store/player.js
server/socket/index.js
server/store/board.js
server/store/gameState.js
server/store/index.js
server/store/players.js

created backend store

---

client/components/Game.js
client/script/circles.js
server/socket/index.js

different players circles draw in different colors now

---

utilityMethods.js

utility methods for path validation

messed w utility methods

---

client/components/Background.js

makes the background to the home screen slightly less graphically intensive

moved around the water plane

---

client/components/Game.js
client/script/drawMap.js
client/script/game.js

general restructure of pixi

---

client/components/Name.js
client/components/ShareLobby.js
client/store/index.js
client/store/title.js
public/style.css

adds css to things and adjusts components. We also have a title now with the random subtitle

fine tuning of css and added to the name compoinent

---

server/socket/lobby.js

fixed the rgb darkener issue for join by id

---

client/script/game.js
client/script/makeFishSprite.js
client/script/makeFisherySprite.js
client/store/fish.js
client/store/fisheries.js

- Add fish label and fishery's socket id/owner
- Refactor store to now create sprite in store like in boat that Chris made. makeFisherySprite and makeFishSprite were created

Fish label

---

client/components/Game.js
fractal-noise.js
server/socket/game.js

start turn

---

client/components/Game.js
client/script/game.js
client/script/makeFisherySprite.js
client/socket/game.js
client/socket/lobby.js
client/store/fisheries.js
client/store/index.js
client/store/pfGrid.js
package-lock.json
package.json
server/script/pathfinding.js
server/socket/game.js
server/store/docks.js
server/store/index.js
server/store/pfGrid.js

initializes the pathfinding grid on game init server-side, and sets it on the client-side store. in both, it's on the state as 'pfGrid'. there is also a 'path' function that makes the actual path, taking starting x, starting y, ending x, ending y, and pfGrid as arguments.

Pathfinding

---

client/socket/game.js
client/socket/lobby.js
server/socket/game.js

moves the socket connections so the server sends stuff to a client that is actually listening

Game init fix

---

client/components/Home.js
client/components/Leaderboards.js
client/components/ShareLobby.js
public/index.html
public/style.css
server/socket/lobby.js

does some cosmetic things, and turns off the ability to rejoin ongoing games (that was used for testing)

Lobby chat leaderboards

---

client/script/game.js
package-lock.json
package.json
public/style.css

Pixi viewport + dark mode 🦇

---

client/components/Game.js
client/script/game.js
client/script/makeFishSprite.js
utilityMethods.js

Collect fishes

---

client/script/game.js
client/script/ifOnFishCollect.js
client/script/makeFishSprite.js

collecting fishes works in simple capacity

---

utilityMethods.js

Adjust getWaterNeighbors

---

client/script/game.js
client/script/makeBoatSprite.js
client/script/makeFishSprite.js
client/script/makeFisherySprite.js
client/socket/lobby.js

fixes fishery visibility and fixes blurry textures

Fishery fix 69

---

client/script/game.js
client/script/makeBoatSprite.js

can only move your own boats

---

client/script/game.js

Boat follow

---

client/components/ControlPanel.js
client/script/CONSTANTS.js
client/script/game.js
client/script/makeBoatSprite.js
client/script/makeFishSprite.js
client/socket/game.js
client/store/index.js
client/store/turnEnded.js
utilityMethods.js

Turn mechanics fixes

---

client/components/Game.js
client/components/Message.js
client/components/PlayerInfo.js
client/components/index.js
client/script/utils/colors.js
public/style.css

Game menu stuff

---

client/components/ControlPanel.js
client/components/Game.js
client/script/drawMap.js
client/script/game.js
client/script/makeBoatSprite.js
client/script/makeMapSprite.js
client/script/makePath.js
client/store/index.js
client/store/pfGrid.js
server/script/pathfinding.js
utilityMethods.js

goes to a random place within range

Boat click go

---

client/components/ControlPanel.js
client/socket/game.js
client/store/index.js
client/store/timer.js
package-lock.json
package.json
server/api/titles/titles.json
server/socket/game.js

- added time limit to turns
- time store client
- game stats updated every turn for leaderboard

turn stuff 2

---

Networking
Redux
client/script/game.js
client/script/ifOnFishCollect.js
client/store/boats.js

Limit boat fishes

---

client/components/AudioPlayer.js
client/components/Game.js
client/components/index.js

audio
- playlist functionality (you can just stick more music in there if you want)

we now have audio

---

public/style.css

small change

---

public/index.html

add semantic ui link

---

client/components/Timer.js
client/script/ifOnFishCollect.js
server/socket/game.js
server/store/turnsRemaining.js

Fix max fish indicator

---

client/components/Home.js
public/index.html

fixed title

---

client/components/BuyBoat.js
client/components/BuyDock.js
public/style.css

Add dubloons

---

client/components/Lobby.js
client/components/Timer.js
client/routes.js
package.json
public/style.css
server/Player.js
server/script/decorations.js
server/socket/game.js
server/store/board.js
server/store/turnsRemaining.js

demo settings we likely want to keep as we add to the game

demo stuff is good

---

server/lobbyer.js

changeserversize

---

client/socket/game.js
server/socket/game.js
server/store/boatNames.js

fixed issue where boat names were inconsistent across clients

Boat name fix

---

client/script/game.js
client/script/ifOnFishCollect.js
client/script/makeBoatSprite.js
client/script/makeFishSprite.js
client/script/utils/makeArrow.js
client/script/utils/setBoatName.js

Got and sold fishes text

---

client/components/EndTurn.js
client/components/GameStats.js
client/script/game.js
client/script/ifOnFishCollect.js
client/script/makeBoatSprite.js
client/script/makeFishSprite.js
client/script/makeFisherySprite.js
client/script/sprites/boatMoveHighlight.js
client/script/sprites/index.js
client/script/utils/boatRange.js
client/script/utils/commitMoves.js
client/script/utils/makeArrow.js
client/script/utils/setBoatName.js
client/socket/game.js
client/store/selectedObject.js
package-lock.json
package.json

- the movement arrow now shows for all of the players boats
- it also disappears when they reach their location
- you can only select one boat at a time
- selection does not remain when a turn ends
- selection status is not incorrect at any point in the process (probably idk anymore)
- centered some of the text things
- fishery name
- boat name
- max fish warning
- made text clearer (no bad blur now)

Boat Click Go V69

---

package.json

seed to postinstall

---

public/index.html

Added analytics tag
